### ISSUE TITLE
Docker installation constantly restarts on new Ubuntu Server VM

### ISSUE THREAD

**Issue by minorsecond** [morph1904/Tyger2#24]
I have a fresh Ubuntu Server 18.04 installation with Docker 19.03.11. After running `docker-compose up -d`, I'm unable to access the installation page. I ran `docker logs Tyger2Beta` and see the following in the log, 

```
2020/06/09 15:34:41 open /apps/Tyger2/data/logs/frontend.log: no such file or directory
Assuming new install
Looks installed, doing nothing
Creating uwsgi.log
Creating uwsgi-access.log
Starting ServicesActivating privacy features... done.
touch: /apps/Tyger2/data/logs/uwsgi.log: No such file or directory
touch: /apps/Tyger2/data/logs/uwsgi-access.log: No such file or directory
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun  9 15:34:45 2020] ***
compiled with version: 9.2.0 on 08 April 2020 20:32:14
os: Linux-4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020
nodename: 7ac525f87082
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
*** starting uWSGI Emperor ***
Assuming new install
Looks installed, doing nothing
Creating uwsgi.log
Creating uwsgi-access.log
Starting ServicesActivating privacy features... done.
2020/06/09 15:34:45 open /apps/Tyger2/data/logs/frontend.log: no such file or directory
```

**Comment by morph1904** [comment]
Hi there. Can you post a copy of your compose file. Also have you ensured that docker has write access to the mapped volumes?

**Comment by minorsecond** [comment]
Hey there.

my docker config follows. Docker does have write permissions to my home directory.

```
version: "3.6"
services:
  Tyger2Beta:
    image: morph1904/tyger2:beta
    container_name: Tyger2Beta
    volumes:
      - /home/rwardrup/tyger2beta/data:/apps/Tyger2/data
      - /home/rwardrup/tyger2beta/data/certs:/root/.caddy
    ports:
      - 443:443
      - 80:80
      - 9090:9090
      - 9091:9091
    restart: unless-stopped
```
