### ISSUE TITLE
Unablet to login 502 error on AJAX request

### ISSUE THREAD

**Issue by morph1904** [morph1904/Tyger2#31]
I have the exact same issue but with the current docker beta image.
Any idea what is wrong with my setting? (Except of not internet accessible)

Within my Firefox I get a bunch of "cross-site access not allowed source:  https://fonts.gstatic.com..." and so no images at login screen. Trying to log in gets me only the _"XHR POST http://server.lab.domain.net:7071/api/api-token-auth/
[HTTP/1.1 502 Bad Gateway 28ms]"_

My portainer setting:
```
version: "2.4"                                                                                                          
services: 
  Tyger2Beta:
    image: morph1904/tyger2:beta
    container_name: tyger2beta
    volumes:
      - tyger2beta_data:/apps/Tyger2/data
      - tyger2beta_certs:/root/.caddy
    ports:
      - 443:443
      - 80:80
      - 7070:9090
      - 7071:9091
    restart: unless-stopped
```

Portainer log:
```
Operations to perform:,
  Apply all migrations: addresses, admin, apps, auth, contenttypes, dns, endpoints, install, sessions,
Running migrations:,
  No migrations to apply.,
  Your models have changes that are not yet reflected in a migration, and so won't be applied.,
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.,
Looks installed, doing nothing,
Creating uwsgi.log,
Creating uwsgi-access.log,
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Oct  9 01:34:40 2020] ***,
compiled with version: 9.3.0 on 01 October 2020 13:57:47,
os: Linux-4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17),
nodename: 440f96a69d03,
machine: x86_64,
clock source: unix,
detected number of CPU cores: 8,
current working directory: /,
detected binary path: /usr/local/bin/uwsgi,
!!! no internal routing support, rebuild with pcre support !!!,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
*** WARNING: you are running uWSGI without its master process manager ***,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
*** starting uWSGI Emperor ***,
Starting ServicesActivating privacy features... done.,
,
Serving HTTP on port 9091 ,
http://:9091/api,
```

BTW: the logo is very similar to "Syncthing" is that on purpose?

_Originally posted by @BlackF09 in https://github.com/morph1904/Tyger2/issue_comments/705918521_
